# Generated by Django 2.2.7 on 2019-11-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrenchVo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='french',
            name='irengname',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='french',
            name='irname',
            field=models.TextField(default='', max_length=100),
        ),
    ]
