# Generated by Django 2.2.7 on 2019-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrenchVo', '0002_auto_20191118_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verbir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irname', models.TextField(max_length=100)),
                ('irengname', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='french',
            name='irengname',
        ),
        migrations.RemoveField(
            model_name='french',
            name='irname',
        ),
    ]
