# Generated by Django 2.2.7 on 2019-11-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrenchVo', '0003_auto_20191118_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ername', models.TextField(max_length=100)),
                ('erengname', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verbre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rename', models.TextField(max_length=100)),
                ('reengname', models.TextField(max_length=100)),
            ],
        ),
    ]
